// Generated by Claude
module;
#define DPL_MODULES 1
#include "dpl/config.h"

#include <cassert>
#include <cstdlib>

export module dpl.test:unary_arithmetic;

import dpl; // provides dpp::*

// Generic test infrastructure for unary arithmetic SIMD operations,
// parameterised on both the DPL CPO and a scalar reference lambda.
//
// Two partial specialisations of unary_arithmetic<A>:
//   fixed_width_abi<A> -- full suite: index_sequence init, bitset masks,
//                          const_mask variants
//   scalable_abi<A>    -- reduced suite: broadcast-based init, runtime loops,
//                          simd mask only (no const_mask; W must be compile-
//                          time for const_mask but scalable lane count is not)
//
// Usage:
//   dpl::test::unary_arithmetic<abi_t>::run_all(dpp::abs, scalar_abs)

namespace dpl::test {

namespace dpp = dpl::datapar;

DPL_EXPORT template <dpp::simd_abi A>
class unary_arithmetic {

    template <typename E>
    using vec_t = dpp::basic_vector<E, A>;

    template <typename E>
    using mask_t = dpp::basic_mask<E, A>;

    template <typename E>
    using abi_traits = dpp::simd_abi_traits<A, E>;

    // Lane count is a compile-time constant for fixed-width ABIs
    template <typename E>
    static constexpr auto lane_count = abi_traits<E>::size();

    // const_mask type aliases -- NTTP values via to_underlying(bitset<W>(...))
    template <dpl::size_t W>
    using alt_cmask_t =
        dpp::const_mask<W, dpl::to_underlying(dpl::bitset<W>(0x5555u))>;

    template <dpl::size_t W>
    using all_cmask_t =
        dpp::const_mask<W, dpl::to_underlying(~dpl::bitset<W>())>;

    template <dpl::size_t W>
    using none_cmask_t =
        dpp::const_mask<W, dpl::to_underlying(dpl::bitset<W>())>;

    template <typename E>
    struct array {
        constexpr array(size_t lanes) : data(new E[lanes]) {}
        constexpr ~array() { delete[] data; }
        array(array const&) = delete;
        array& operator=(array const&) = delete;
        E* data;
    };

    // ---- unmasked ----------------------------------------------------------

    template <typename E, dpl::size_t... Is>
    static constexpr void test_unmasked(
        auto op, auto scalar_op, dpl::index_sequence<Is...>)
    requires dpp::fixed_width_abi<A>
    {
        using U = dpp::unsigned_representation_t<E>;

        constexpr E in_vals[sizeof...(Is)] = {
            static_cast<E>((Is % 2zu == 0) ? static_cast<E>(Is + 1)
                                           : -static_cast<E>(Is + 1))...};

        auto v = dpp::initialize<E, A>(in_vals[Is]...);
        auto r = op(v);

        ((assert(dpl::bit_cast<U>(dpp::extract(r, Is)) ==
             dpl::bit_cast<U>(scalar_op(in_vals[Is])))),
            ...);

        // op(0) == scalar_op(0)
        {
            auto z = dpp::broadcast<E, A>(static_cast<E>(0));
            auto rz = op(z);
            ((assert(dpl::bit_cast<U>(dpp::extract(rz, Is)) ==
                 dpl::bit_cast<U>(scalar_op(static_cast<E>(0))))),
                ...);
        }
    }

    // ---- masked ------------------------------------------------------------

    template <typename E, dpl::size_t... Is>
    static constexpr void test_masked(
        auto op, auto scalar_op, dpl::index_sequence<Is...>)
    requires dpp::fixed_width_abi<A>
    {
        constexpr auto lanes = sizeof...(Is);
        using U = dpp::unsigned_representation_t<E>;

        constexpr E in_vals[lanes] = {
            static_cast<E>((Is % 2zu == 0) ? static_cast<E>(Is + 1)
                                           : -static_cast<E>(Is + 1))...};
        auto val = dpp::initialize<E, A>(in_vals[Is]...);
        auto src = dpp::broadcast<E, A>(static_cast<E>(99));

        auto b_alt = dpl::truncate<lanes>(dpl::bitset<A::size>(0x5555u));
        auto b_all = dpl::truncate<lanes>(~dpl::bitset<A::size>());
        auto b_none = dpl::bitset<lanes>{};

        auto simd_alt = dpp::from_bitset<E, A>(b_alt);
        auto simd_all = dpp::from_bitset<E, A>(b_all);
        auto simd_none = dpp::from_bitset<E, A>(b_none);

        auto check_merge = [&](vec_t<E> r, dpl::bitset<lanes> mb) {
            for (auto i = 0zu; i < lanes; ++i) {
                U const got = dpl::bit_cast<U>(dpp::extract(r, i));
                U const exp = mb[i] ? dpl::bit_cast<U>(scalar_op(in_vals[i]))
                                    : dpl::bit_cast<U>(dpp::extract(src, i));
                assert(got == exp);
            }
        };

        auto check_zero = [&](vec_t<E> r, dpl::bitset<lanes> mb) {
            for (auto i = 0zu; i < lanes; ++i) {
                U const got = dpl::bit_cast<U>(dpp::extract(r, i));
                U const exp =
                    mb[i] ? dpl::bit_cast<U>(scalar_op(in_vals[i])) : U(0);
                assert(got == exp);
            }
        };

        // simd mask forms
        check_merge(op(src, simd_alt, val), b_alt);
        check_merge(op(src, simd_all, val), b_all);
        check_merge(op(src, simd_none, val), b_none);
        check_zero(op(dpp::zero, simd_alt, val), b_alt);
        check_zero(op(dpp::zero, simd_all, val), b_all);
        check_zero(op(dpp::zero, simd_none, val), b_none);
        check_zero(op(simd_alt, val), b_alt);
        check_zero(op(simd_all, val), b_all);
        check_zero(op(simd_none, val), b_none);

        // const_mask forms -- fixed_width_abi only
        {
            using cmask_alt = alt_cmask_t<lanes>;
            using cmask_all = all_cmask_t<lanes>;
            using cmask_none = none_cmask_t<lanes>;

            check_merge(op(src, cmask_alt{}, val), b_alt);
            check_merge(op(src, cmask_all{}, val), b_all);
            check_merge(op(src, cmask_none{}, val), b_none);
            check_zero(op(dpp::zero, cmask_alt{}, val), b_alt);
            check_zero(op(dpp::zero, cmask_all{}, val), b_all);
            check_zero(op(dpp::zero, cmask_none{}, val), b_none);
            check_zero(op(cmask_alt{}, val), b_alt);
            check_zero(op(cmask_all{}, val), b_all);
            check_zero(op(cmask_none{}, val), b_none);
        }
    }

    // ---- FP special values -------------------------------------------------

    template <typename E>
    static constexpr void test_fp_special(auto op, auto scalar_op) {
        using uint = dpp::unsigned_representation_t<E>;
        auto const check_one = [&](E pattern, E* data) {
            E const input = dpl::bit_cast<E>(pattern);
            E const expected = scalar_op(input);
            auto r = op(dpp::broadcast<E, A>(input));
            dpp::store(r, data);
            for (auto i = 0zu; i < vec_t<E>::size(); ++i) {
                assert(dpl::bit_cast<uint>(data[i]) ==
                    dpl::bit_cast<uint>(expected));
            }
        };

        if constexpr (dpp::fixed_width_abi<E>) {
            E data[vec_t<E>::size()]{};
            check_one(dpp::msb_v<E>, data);       // -0.0
            check_one(-dpp::infinity_v<E>, data); // -inf
            check_one(dpp::infinity_v<E>, data);  // +inf
            check_one(dpp::nan_v<E>, data);       // -nan
            check_one(-dpp::nan_v<E>, data);      // nan
            // should we do signaling nans?
        } else {
            array<E> const buffer(vec_t<E>::size());
            check_one(dpp::msb_v<E>, buffer.data);       // -0.0
            check_one(-dpp::infinity_v<E>, buffer.data); // -inf
            check_one(dpp::infinity_v<E>, buffer.data);  // +inf
            check_one(dpp::nan_v<E>, buffer.data);       // -nan
            check_one(-dpp::nan_v<E>, buffer.data);      // nan
        }
    }

    // ---- per-type dispatchers ----------------------------------------------

    template <typename E>
    static constexpr void test_unmasked(auto op, auto scalar_op) {
        if constexpr (dpp::fixed_width_abi<A>) {
            test_unmasked<E>(
                op, scalar_op, dpl::make_index_sequence<lane_count<E>>{});
        } else {
            using U = dpp::unsigned_representation_t<E>;
            auto const lanes = vec_t<E>::size();
            array<E> const buffer(lanes);
            // Test with a positive and a negative broadcast value
            for (E input : {static_cast<E>(5), static_cast<E>(-5)}) {
                E const expected = scalar_op(input);
                auto v = dpp::broadcast<E, A>(input);
                auto r = op(v);
                dpp::store(r, buffer.data);
                for (auto i = 0zu; i < lanes; ++i)
                    assert(dpl::bit_cast<U>(buffer.data[i]) ==
                        dpl::bit_cast<U>(expected));
            }

            // op(0) == scalar_op(0)
            {
                E const expected = scalar_op(static_cast<E>(0));
                auto z = dpp::broadcast<E, A>(static_cast<E>(0));
                auto rz = op(z);

                dpp::store(rz, buffer.data);
                for (auto i = 0zu; i < lanes; ++i)
                    assert(dpl::bit_cast<U>(buffer.data[i]) ==
                        dpl::bit_cast<U>(expected));
            }

            if not consteval {
                if constexpr (dpl::signed_integral<E>) {
                    auto vmin = dpp::broadcast<E, A>(dpp::min_value);
                    auto rmin = op(vmin);
                    dpp::store(rmin, buffer.data);
                    U const exp =
                        dpl::bit_cast<U>(scalar_op(dpp::min_value_v<E>));
                    for (auto i = 0zu; i < lanes; ++i)
                        assert(dpl::bit_cast<U>(buffer.data[i]) == exp);
                }
            }
        }
    }

    template <typename E>
    static constexpr void test_masked(auto op, auto scalar_op) {
        if constexpr (dpp::fixed_width_abi<A>) {
            test_masked<E>(
                op, scalar_op, dpl::make_index_sequence<lane_count<E>>{});
        } else {
            auto const val = dpp::broadcast<E, A>(static_cast<E>(-5));
            auto const src = dpp::broadcast<E, A>(static_cast<E>(99));
            E const expected_active = scalar_op(static_cast<E>(-5));

            auto const all_true = dpp::broadcast<E, A>(true);
            auto const all_false = dpp::broadcast<E, A>(false);
            auto const alt_mask = (dpp::lane_index<A, E>() & 1) != 0;
            auto const op_val = op(val);
            auto const vzero = dpp::broadcast<E, A>(dpp::zero);

            {
                assert(dpp::all_of(op(src, all_true, val) == op_val));
                assert(dpp::none_of(op(src, all_false, val) == op_val));
                assert(dpp::all_of(op(src, all_false, val) == src));

                auto const actual = op(src, alt_mask, val);
                assert(dpp::all_of((actual == op_val) == alt_mask));
                assert(dpp::all_of((actual == src) == !alt_mask));
            }

            {
                assert(dpp::all_of(op(vzero, all_true, val) == //
                    op(dpp::zero, all_true, val)));
                assert(dpp::all_of(op(vzero, all_false, val) == //
                    op(dpp::zero, all_false, val)));
                assert(dpp::all_of(op(vzero, alt_mask, val) == //
                    op(dpp::zero, alt_mask, val)));
            }

            {
                assert(dpp::all_of(
                    op(all_true, val) == op(dpp::zero, all_true, val)));
                assert(dpp::all_of(
                    op(all_false, val) == op(dpp::zero, all_false, val)));
                assert(dpp::all_of(
                    op(alt_mask, val) == op(dpp::zero, alt_mask, val)));
            }
        }
    }

    template <typename E>
    static constexpr void test(auto op, auto scalar_op) {
        test_unmasked<E>(op, scalar_op);
        test_masked<dpl::int8>(op, scalar_op);
        if constexpr (!dpl::integral<E>) {
            test_fp_special<E>(op, scalar_op);
        }
    }

public:
    static constexpr bool run_all(auto op, auto scalar_op) {
        test<dpl::int8>(op, scalar_op);
        test<dpl::uint8>(op, scalar_op);
        test<dpl::int16>(op, scalar_op);
        test<dpl::uint16>(op, scalar_op);
        test<dpl::int32>(op, scalar_op);
        test<dpl::uint32>(op, scalar_op);
        test<dpl::int64>(op, scalar_op);
        test<dpl::uint64>(op, scalar_op);
        test<float>(op, scalar_op);
        test<double>(op, scalar_op);
#if DPL_SUPPORTS_FLOAT16
        test<dpl::float16>(op, scalar_op);
#endif
#if DPL_SUPPORTS_BFLOAT16
        test<dpl::bfloat16>(op, scalar_op);
#endif
        return true;
    }

    template <dpp::simd_element_for<A> E>
    static constexpr bool test_value(E arg, auto op, auto scalar_op) {
        auto const vmin = dpp::broadcast<E, A>(arg);
        auto const expected = dpp::broadcast<E, A>(scalar_op(arg));
        assert(dpp::all_of(op(vmin) == expected));
        return true;
    }
};

} // namespace dpl::test
