// Copyright 2025 Bryan Wong
module;

#define DPL_MODULES 1
#include "dpl/config.h"

export module dpl:std.type_traits;
export import :std.stddef;

// IWYU pragma: begin_exports
#include "dpl/std/type_traits/add_const.h"
#include "dpl/std/type_traits/add_lvalue_reference.h"
#include "dpl/std/type_traits/add_pointer.h"
#include "dpl/std/type_traits/add_rvalue_reference.h"
#include "dpl/std/type_traits/add_volatile.h"
#include "dpl/std/type_traits/common_reference.h"
#include "dpl/std/type_traits/common_type.h"
#include "dpl/std/type_traits/conditional.h"
#include "dpl/std/type_traits/constants.h"
#include "dpl/std/type_traits/copy_cv.h"
#include "dpl/std/type_traits/copy_cvref.h"
#include "dpl/std/type_traits/enable_if.h"
#include "dpl/std/type_traits/extent.h"
#include "dpl/std/type_traits/has_unique_object_representations.h"
#include "dpl/std/type_traits/is_aggregate.h"
#include "dpl/std/type_traits/is_arithmetic.h"
#include "dpl/std/type_traits/is_array.h"
#include "dpl/std/type_traits/is_assignable.h"
#include "dpl/std/type_traits/is_base_of.h"
#include "dpl/std/type_traits/is_bounded_array.h"
#include "dpl/std/type_traits/is_class.h"
#include "dpl/std/type_traits/is_const.h"
#include "dpl/std/type_traits/is_constructible.h"
#include "dpl/std/type_traits/is_convertible.h"
#include "dpl/std/type_traits/is_destructible.h"
#include "dpl/std/type_traits/is_empty.h"
#include "dpl/std/type_traits/is_enum.h"
#include "dpl/std/type_traits/is_final.h"
#include "dpl/std/type_traits/is_floating_point.h"
#include "dpl/std/type_traits/is_function.h"
#include "dpl/std/type_traits/is_implicit_lifetime.h"
#include "dpl/std/type_traits/is_integral.h"
#include "dpl/std/type_traits/is_invocable.h"
#include "dpl/std/type_traits/is_lvalue_reference.h"
#include "dpl/std/type_traits/is_member_function_pointer.h"
#include "dpl/std/type_traits/is_member_object_pointer.h"
#include "dpl/std/type_traits/is_member_pointer.h"
#include "dpl/std/type_traits/is_nothrow_assignable.h"
#include "dpl/std/type_traits/is_nothrow_constructible.h"
#include "dpl/std/type_traits/is_nothrow_convertible.h"
#include "dpl/std/type_traits/is_nothrow_destructible.h"
#include "dpl/std/type_traits/is_null_pointer.h"
#include "dpl/std/type_traits/is_object.h"
#include "dpl/std/type_traits/is_pointer.h"
#include "dpl/std/type_traits/is_reference.h"
#include "dpl/std/type_traits/is_rvalue_reference.h"
#include "dpl/std/type_traits/is_same.h"
#include "dpl/std/type_traits/is_scalar.h"
#include "dpl/std/type_traits/is_scoped_enum.h"
#include "dpl/std/type_traits/is_signed.h"
#include "dpl/std/type_traits/is_standard_layout.h"
#include "dpl/std/type_traits/is_trivially_assignable.h"
#include "dpl/std/type_traits/is_trivially_constructible.h"
#include "dpl/std/type_traits/is_trivially_copyable.h"
#include "dpl/std/type_traits/is_trivially_destructible.h"
#include "dpl/std/type_traits/is_unbounded_array.h"
#include "dpl/std/type_traits/is_union.h"
#include "dpl/std/type_traits/is_unsigned.h"
#include "dpl/std/type_traits/is_void.h"
#include "dpl/std/type_traits/is_volatile.h"
#include "dpl/std/type_traits/make_signed.h"
#include "dpl/std/type_traits/make_unsigned.h"
#include "dpl/std/type_traits/remove_const.h"
#include "dpl/std/type_traits/remove_cvref.h"
#include "dpl/std/type_traits/remove_reference.h"
#include "dpl/std/type_traits/type_identity.h"
#include "dpl/std/type_traits/underlying_type.h"
#include "dpl/std/type_traits/void_t.h"
// IWYU pragma: end_exports
