// Copyright 2025-2026 Bryan Wong

// GCC has a large default
// @dpl[clang].compile-flags: -fconstexpr-steps=2000000
// @dpl[msvc].compile-flags: /constexpr:steps2000000

#include "dpl/config.h"

#include <cassert>

import dpl.xmm;
import dpl.test;

// Comment generated by Claude
// Tests for dpp::abs on xmm ABI. Requires SSE4.2 (implied by dpl.xmm).
//
// Forms tested:
//   (1) dpp::abs(val)                  -- unmasked, always available
//   (2) dpp::abs(src, mask, val)       -- merge-masked
//   (3) dpp::abs(dpp::zero, mask, val) -- zero-masked explicit
//   (4) dpp::abs(mask, val)            -- zero-masked alias (== form 3)
//
// INT_MIN: abs(INT_MIN) == INT_MIN on 2's complement hardware (wraps).
// Float special cases (-0.0, ±inf, NaN) compared via bit_cast since
// NaN != NaN under IEEE 754.

int main() {
    namespace dpp = dpl::datapar;
    namespace xmm = dpl::datapar::xmm;
    static constexpr auto expected = []<typename E>(E v) constexpr -> E {
        if constexpr (dpl::unsigned_integral<E>) {
            return v;
        } else if constexpr (dpl::integral<E>) {
            using U = dpp::unsigned_representation_t<E>;
            return v < E(0) ? static_cast<E>(-static_cast<U>(v)) : v;
        } else {
            using U = dpp::unsigned_representation_t<E>;
            constexpr U sign_mask = U(1) << (sizeof(E) * dpl::char_bit_v - 1u);
            return dpl::bit_cast<E>(
                static_cast<U>(dpl::bit_cast<U>(v) & ~sign_mask));
        }
    };

    using abi_t = xmm::abi_tag;
    static_assert(
        dpl::test::unary_arithmetic<abi_t>::run_all(dpp::abs, expected));
    assert(dpl::test::unary_arithmetic<abi_t>::run_all(dpp::abs, expected));

    // below is runtime only -min_value is implementation defined and not
    // allowed at consteval
    assert(dpl::test::unary_arithmetic<abi_t>::test_value<dpl::int8>(
        dpp::min_value, dpp::abs, expected));
    assert(dpl::test::unary_arithmetic<abi_t>::test_value<dpl::int16>(
        dpp::min_value, dpp::abs, expected));
    assert(dpl::test::unary_arithmetic<abi_t>::test_value<dpl::int32>(
        dpp::min_value, dpp::abs, expected));
    assert(dpl::test::unary_arithmetic<abi_t>::test_value<dpl::int64>(
        dpp::min_value, dpp::abs, expected));
    return 0;
}
