// Copyright 2025-2026 Bryan Wong

// GCC has a large default
// @dpl[clang].compile-flags: -fconstexpr-steps=2000000
// @dpl[msvc].compile-flags: /constexpr:steps2000000

#include "dpl/config.h"

#include <cassert>

import dpl.xmm;
import dpl.test;

// Comment generated by Claude
// Tests for dpp::abs on xmm ABI. Requires SSE4.2 (implied by dpl.xmm).
//
// Forms tested:
//   (1) dpp::abs(val)                  -- unmasked, always available
//   (2) dpp::abs(src, mask, val)       -- merge-masked
//   (3) dpp::abs(dpp::zero, mask, val) -- zero-masked explicit
//   (4) dpp::abs(mask, val)            -- zero-masked alias (== form 3)
//
// INT_MIN: abs(INT_MIN) == INT_MIN on 2's complement hardware (wraps).
// Float special cases (-0.0, ±inf, NaN) compared via bit_cast since
// NaN != NaN under IEEE 754.

int main() {
    namespace dpp = dpl::datapar;
    namespace xmm = dpl::datapar::xmm;
    using abi_t = xmm::abi_tag;

    using types = dpl::type_pack<dpl::int8, dpl::uint8, dpl::int16, dpl::uint16,
        dpl::int32, dpl::uint32, dpl::int64, dpl::uint64, float, double,
        dpl::ext::float16, dpl::ext::bfloat16>;

    constexpr auto run_tests = []<typename E>(dpl::type_identity<E> type) {
        constexpr auto expected_op = [](E v) {
            if constexpr (dpl::unsigned_integral<E>) {
                return v;
            } else if constexpr (dpl::integral<E>) {
                using U = dpp::unsigned_representation_t<E>;
                return v < E(0) ? static_cast<E>(-static_cast<U>(v)) : v;
            } else {
                using U = dpp::unsigned_representation_t<E>;
                constexpr U sign_mask = U(1)
                    << (sizeof(E) * dpl::char_bit_v - 1u);
                return dpl::bit_cast<E>(
                    static_cast<U>(dpl::bit_cast<U>(v) & ~sign_mask));
            }
        };

        dpl::test::mt19937 engine(
            dpl::type_bit_v<E> % 31 + dpl::floating_point_like<E>);
        dpl::test::array_generator<abi_t, E> const data_generator(
            dpl::test::half_range);
        dpl::test::scalar_generator<E> const src_generator(
            dpp::max_value_v<E> / 4 * 3, dpp::max_value_v<E>);

        auto const data = data_generator(engine);
        auto const src = src_generator(engine);
        auto expected = data;
        for (auto& val : expected) {
            val = expected_op(val);
        }

        dpl::test::unary_transform<abi_t>::test<E>(data, dpp::abs, expected);
        dpl::test::unary_transform<abi_t>::test_masked<E>(data, dpp::abs, src);

        if constexpr (dpl::signed_integral<E>) {
            if not consteval {
                // Implementation-defined
                auto const min = dpl::integral_traits<E>::min_value;
                dpl::test::unary_transform<abi_t>::test(min, dpp::abs, min);
            }
        }

        if constexpr (dpl::floating_point_like<E>) {
            for (auto const arg :
                dpl::test::array{dpp::msb_v<E>, -dpp::infinity_v<E>,
                    dpp::infinity_v<E>, -dpp::nan_v<E>, dpp::nan_v<E>}) {

                auto const expected = expected_op(arg);
                dpl::test::unary_transform<abi_t>::test(
                    arg, dpp::abs, expected, dpl::test::bitcmp);
            }
        }

        return true;
    };

    dpl::pack::for_each(
        [=](auto tp) {
            static_assert(run_tests(tp));
            assert(run_tests(tp));
        },
        types{});
    return 0;
}
