// Copyright 2025-2026 Bryan Wong
// @dpl[clang].compile-flags: -fconstexpr-steps=2000000
// @dpl[msvc].compile-flags: /constexpr:steps2000000
#include "../common.h"

import dpl.xmm;
import dpl.test.harness.operations.signop;

// Comment generated by Claude
// Tests for dpp::negate on xmm ABI. Requires SSE4.2 (implied by dpl.xmm).
//
// Forms tested:
//   (1) dpp::negate(val)                  -- unmasked, always available
//   (2) dpp::negate(src, mask, val)       -- merge-masked
//   (3) dpp::negate(dpp::zero, mask, val) -- zero-masked explicit
//   (4) dpp::negate(mask, val)            -- zero-masked alias (== form 3)

int main() {
    namespace dpp = dpl::datapar;
    namespace xmm = dpl::datapar::xmm;
    using abi_t = xmm::abi_tag;
    using types = dpl::type_pack<dpl::int8, dpl::uint8, dpl::int16, dpl::uint16,
        dpl::int32, dpl::uint32, dpl::int64, dpl::uint64, float, double,
        dpl::ext::float16, dpl::ext::bfloat16>;
    constexpr auto run = []() {
        dpl::test::mt19937 engine;
        return dpl::test::signop<abi_t>::run_all<dpp::negate>(types{}, engine);
    };

    static_assert(run());
    assert(run());
    return 0;
}
