// Copyright 2025-2026 Bryan Wong

// GCC has a large default
// @dpl[clang].compile-flags: -fconstexpr-steps=2000000
// @dpl[msvc].compile-flags: /constexpr:steps2000000

#include "../common.h"

import dpl.xmm;
import dpl.test;

// Comment generated by Claude
// Tests for dpp::negate on xmm ABI. Requires SSE4.2 (implied by dpl.xmm).
//
// Forms tested:
//   (1) dpp::negate(val)                  -- unmasked, always available
//   (2) dpp::negate(src, mask, val)       -- merge-masked
//   (3) dpp::negate(dpp::zero, mask, val) -- zero-masked explicit
//   (4) dpp::negate(mask, val)            -- zero-masked alias (== form 3)
//
// INT_MIN: negate(INT_MIN) == INT_MIN on 2's complement hardware (wraps).
// Float special cases (-0.0, ±inf, NaN) compared via bit_cast since
// NaN != NaN under IEEE 754.

int main() {
    namespace dpp = dpl::datapar;
    namespace xmm = dpl::datapar::xmm;
    static constexpr auto expected = []<typename E>(E v) constexpr -> E {
        if constexpr (dpl::integral<E>) {
            return -v;
        } else {
            using U = dpp::unsigned_representation_t<E>;
            constexpr U sign_mask = dpl::bit_cast<U>(dpp::msb_v<E>);
            return dpl::bit_cast<E>(
                static_cast<U>(dpl::bit_cast<U>(v) ^ sign_mask));
        }
    };

    using abi_t = xmm::abi_tag;
    static_assert(
        dpl::test::unary_arithmetic<abi_t>::run_all(dpp::negate, expected));
    assert(dpl::test::unary_arithmetic<abi_t>::run_all(dpp::negate, expected));

    // below is runtime only -min_value is implementation defined and not
    // allowed at consteval
    assert(dpl::test::unary_arithmetic<abi_t>::test_value<dpl::int8>(
        dpp::min_value, dpp::negate, expected));
    assert(dpl::test::unary_arithmetic<abi_t>::test_value<dpl::int16>(
        dpp::min_value, dpp::negate, expected));
    assert(dpl::test::unary_arithmetic<abi_t>::test_value<dpl::int32>(
        dpp::min_value, dpp::negate, expected));
    assert(dpl::test::unary_arithmetic<abi_t>::test_value<dpl::int64>(
        dpp::min_value, dpp::negate, expected));
    return 0;
}
