// Copyright 2025-2026 Bryan Wong

// GCC has a large default
// @dpl[clang].compile-flags: -fconstexpr-steps=2000000
// @dpl[msvc].compile-flags: /constexpr:steps2000000

#include "../common.h"

import dpl.xmm;
import dpl.test;

// Comment generated by Claude
// Tests for dpp::negate on xmm ABI. Requires SSE4.2 (implied by dpl.xmm).
//
// Forms tested:
//   (1) dpp::negate(val)                  -- unmasked, always available
//   (2) dpp::negate(src, mask, val)       -- merge-masked
//   (3) dpp::negate(dpp::zero, mask, val) -- zero-masked explicit
//   (4) dpp::negate(mask, val)            -- zero-masked alias (== form 3)
//
// INT_MIN: negate(INT_MIN) == INT_MIN on 2's complement hardware (wraps).
// Float special cases (-0.0, ±inf, NaN) compared via bit_cast since
// NaN != NaN under IEEE 754.

int main() {
    namespace dpp = dpl::datapar;
    namespace xmm = dpl::datapar::xmm;
    using abi_t = xmm::abi_tag;

    using types = dpl::type_pack<dpl::int8, dpl::uint8, dpl::int16, dpl::uint16,
        dpl::int32, dpl::uint32, dpl::int64, dpl::uint64, float, double,
        dpl::ext::float16, dpl::ext::bfloat16>;

    constexpr auto run_tests = []<typename E>(dpl::type_identity<E> type) {
        constexpr auto expected_op = [](E v) {
            if constexpr (dpl::integral<E>) {
                return -v;
            } else {
                using U = dpp::unsigned_representation_t<E>;
                constexpr U sign_mask = dpl::bit_cast<U>(dpp::msb_v<E>);
                return dpl::bit_cast<E>(
                    static_cast<U>(dpl::bit_cast<U>(v) ^ sign_mask));
            }
        };

        auto const data = dpl::test::data_provider<abi_t>::template array<E>();
        auto const src = dpl::test::data_provider<abi_t>::template src<E>();
        auto expected = data;
        for (auto& val : expected) {
            val = expected_op(val);
        }

        dpl::test::unary_transform<abi_t>::test<E>(data, dpp::negate, expected);
        dpl::test::unary_transform<abi_t>::test_masked<E>(
            data, dpp::negate, src);

        if constexpr (dpl::signed_integral<E>) {
            if not consteval {
                // Implementation-defined
                auto const min = dpl::integral_traits<E>::min_value;
                dpl::test::unary_transform<abi_t>::test(min, dpp::negate, min);
            }
        }

        if constexpr (dpl::floating_point_like<E>) {
            for (auto const arg :
                dpl::test::array{dpp::msb_v<E>, -dpp::infinity_v<E>,
                    dpp::infinity_v<E>, -dpp::nan_v<E>, dpp::nan_v<E>}) {

                auto const expected = expected_op(arg);
                dpl::test::unary_transform<abi_t>::test(
                    arg, dpp::negate, expected, dpl::test::bitcmp);
            }
        }

        return true;
    };

    dpl::pack::for_each(
        [=](auto tp) {
            static_assert(run_tests(tp));
            assert(run_tests(tp));
        },
        types{});
    return 0;
}
