/* Copyright 2023-2025 Bryan Wong */

#pragma once

#include "configuration/utl_compiler.h"
#include "configuration/utl_declspec.h"

#include "preprocessor/utl_apply_macro.h"
#include "preprocessor/utl_concatenation.h"
#include "preprocessor/utl_is_empty.h"
#include "preprocessor/utl_paste.h"

#define __DPL_CPP_ATTRIBUTE_SCOPE_1()
#define __DPL_CPP_ATTRIBUTE_SCOPE_0(...) [[__VA_ARGS__]]
#define __DPL_CPP_ATTRIBUTE_SCOPE(...) \
    DPL_PASTE(DPL_APPEND_IS_EMPTY(__DPL_CPP_ATTRIBUTE_SCOPE_, __VA_ARGS__)(__VA_ARGS__))

#define __DPL_GNU_ATTRIBUTE_SCOPE_1()
#define __DPL_GNU_ATTRIBUTE_SCOPE_0(...) __attribute__((__VA_ARGS__))
#define __DPL_GNU_ATTRIBUTE_SCOPE(...) \
    DPL_PASTE(DPL_APPEND_IS_EMPTY(__DPL_GNU_ATTRIBUTE_SCOPE_, __VA_ARGS__)(__VA_ARGS__))

#define __DPL_DECLSPEC_SCOPE_1()
#define __DPL_DECLSPEC_SCOPE_0(...) __declspec(__VA_ARGS__)
#define __DPL_DECLSPEC_SCOPE(...) \
    DPL_PASTE(DPL_APPEND_IS_EMPTY(__DPL_DECLSPEC_SCOPE_, __VA_ARGS__)(__VA_ARGS__))

#define __DPL_TRANSLATE_ATTRIBUTE(ARGS) DPL_SWAP_CONCAT(_END, __DPL_TRANSLATE_ATTRIBUTE_1 ARGS)
#define __DPL_TRANSLATE_ATTRIBUTE_0(NAME) (DPL_CONCAT(__DPL_ATTRIBUTE_, NAME))
#if DPL_MSVC_PREPROCESSOR
#  define __DPL_TRANSLATE_ATTRIBUTE_1(NAME) \
      DPL_PASTE(__DPL_TRANSLATE_ATTRIBUTE_0(NAME) __DPL_TRANSLATE_ATTRIBUTE_2)
#  define __DPL_TRANSLATE_ATTRIBUTE_2(NAME) \
      DPL_PASTE(__DPL_TRANSLATE_ATTRIBUTE_0(NAME) __DPL_TRANSLATE_ATTRIBUTE_1)
#else
#  define __DPL_TRANSLATE_ATTRIBUTE_1(NAME) \
      __DPL_TRANSLATE_ATTRIBUTE_0(NAME) __DPL_TRANSLATE_ATTRIBUTE_2
#  define __DPL_TRANSLATE_ATTRIBUTE_2(NAME) \
      __DPL_TRANSLATE_ATTRIBUTE_0(NAME) __DPL_TRANSLATE_ATTRIBUTE_1
#endif
#define __DPL_TRANSLATE_ATTRIBUTE_1_END
#define __DPL_TRANSLATE_ATTRIBUTE_2_END

#define __DPL_BUILD_ATTRIBUTE_LIST(ARGS) DPL_SWAP_CONCAT(_END, __DPL_BUILD_ATTRIBUTE_LIST_1 ARGS)
#define __DPL_BEGIN_ATTRIBUTE_LIST(NAME) NAME
#define __DPL_APPEND_ATTRIBUTE(NAME) , NAME
#if DPL_MSVC_PREPROCESSOR
#  define __DPL_BUILD_ATTRIBUTE_LIST_1(MEMBER) \
      DPL_PASTE(__DPL_BEGIN_ATTRIBUTE_LIST(MEMBER) __DPL_BUILD_ATTRIBUTE_LIST_2)
#  define __DPL_BUILD_ATTRIBUTE_LIST_2(MEMBER) \
      DPL_PASTE(__DPL_APPEND_ATTRIBUTE(MEMBER) __DPL_BUILD_ATTRIBUTE_LIST_3)
#  define __DPL_BUILD_ATTRIBUTE_LIST_3(MEMBER) \
      DPL_PASTE(__DPL_APPEND_ATTRIBUTE(MEMBER) __DPL_BUILD_ATTRIBUTE_LIST_2)
#else
#  define __DPL_BUILD_ATTRIBUTE_LIST_1(MEMBER) \
      __DPL_BEGIN_ATTRIBUTE_LIST(MEMBER) __DPL_BUILD_ATTRIBUTE_LIST_2
#  define __DPL_BUILD_ATTRIBUTE_LIST_2(MEMBER) \
      __DPL_APPEND_ATTRIBUTE(MEMBER) __DPL_BUILD_ATTRIBUTE_LIST_3
#  define __DPL_BUILD_ATTRIBUTE_LIST_3(MEMBER) \
      __DPL_APPEND_ATTRIBUTE(MEMBER) __DPL_BUILD_ATTRIBUTE_LIST_2
#endif
#define __DPL_BUILD_ATTRIBUTE_LIST_1_END
#define __DPL_BUILD_ATTRIBUTE_LIST_2_END
#define __DPL_BUILD_ATTRIBUTE_LIST_3_END

#define __DPL_ATTRIBUTE_FILTER_1(NAME) (NAME)
#define __DPL_ATTRIBUTE_FILTER_0(X)
#define __DPL_ATTRIBUTE_FILTER(NAME, ...) \
    DPL_PASTE(DPL_APPEND_IS_EMPTY(__DPL_ATTRIBUTE_FILTER_, __VA_ARGS__)(NAME))

#define __DPL_FILTER_CPP_ATTRIBUTES(ARGS) DPL_SWAP_CONCAT(_END, __DPL_FILTER_CPP_ATTRIBUTES_1 ARGS)
#define __DPL_FILTER_CPP_ATTRIBUTES_1(NAME)                                   \
    __DPL_ATTRIBUTE_FILTER(NAME, DPL_CONCAT(__DPL_ATTRIBUTE_TYPE_CPP_, NAME)) \
    __DPL_FILTER_CPP_ATTRIBUTES_2
#define __DPL_FILTER_CPP_ATTRIBUTES_2(NAME)                                   \
    __DPL_ATTRIBUTE_FILTER(NAME, DPL_CONCAT(__DPL_ATTRIBUTE_TYPE_CPP_, NAME)) \
    __DPL_FILTER_CPP_ATTRIBUTES_1
#define __DPL_FILTER_CPP_ATTRIBUTES_1_END
#define __DPL_FILTER_CPP_ATTRIBUTES_2_END

#define __DPL_CPP_ATTRIBUTES(LIST) \
    __DPL_CPP_ATTRIBUTE_SCOPE(     \
        __DPL_BUILD_ATTRIBUTE_LIST(__DPL_TRANSLATE_ATTRIBUTE(__DPL_FILTER_CPP_ATTRIBUTES(LIST))))

#define __DPL_FILTER_GNU_ATTRIBUTES(ARGS) DPL_SWAP_CONCAT(_END, __DPL_FILTER_GNU_ATTRIBUTES_1 ARGS)
#define __DPL_FILTER_GNU_ATTRIBUTES_1(NAME)                                   \
    __DPL_ATTRIBUTE_FILTER(NAME, DPL_CONCAT(__DPL_ATTRIBUTE_TYPE_GNU_, NAME)) \
    __DPL_FILTER_GNU_ATTRIBUTES_2
#define __DPL_FILTER_GNU_ATTRIBUTES_2(NAME)                                   \
    __DPL_ATTRIBUTE_FILTER(NAME, DPL_CONCAT(__DPL_ATTRIBUTE_TYPE_GNU_, NAME)) \
    __DPL_FILTER_GNU_ATTRIBUTES_1
#define __DPL_FILTER_GNU_ATTRIBUTES_1_END
#define __DPL_FILTER_GNU_ATTRIBUTES_2_END

#define __DPL_GNU_ATTRIBUTES(LIST) \
    __DPL_GNU_ATTRIBUTE_SCOPE(     \
        __DPL_BUILD_ATTRIBUTE_LIST(__DPL_TRANSLATE_ATTRIBUTE(__DPL_FILTER_GNU_ATTRIBUTES(LIST))))

#if DPL_SUPPORTS_DECLSPEC
#  define __DPL_FILTER_DECLSPEC_ATTRIBUTES(ARGS) \
      DPL_SWAP_CONCAT(_END, __DPL_FILTER_DECLSPEC_ATTRIBUTES_1 ARGS)
#  define __DPL_FILTER_DECLSPEC_ATTRIBUTES_1(NAME)                                   \
      __DPL_ATTRIBUTE_FILTER(NAME, DPL_CONCAT(__DPL_ATTRIBUTE_TYPE_DECLSPEC_, NAME)) \
      __DPL_FILTER_DECLSPEC_ATTRIBUTES_2
#  define __DPL_FILTER_DECLSPEC_ATTRIBUTES_2(NAME)                                   \
      __DPL_ATTRIBUTE_FILTER(NAME, DPL_CONCAT(__DPL_ATTRIBUTE_TYPE_DECLSPEC_, NAME)) \
      __DPL_FILTER_DECLSPEC_ATTRIBUTES_1
#  define __DPL_FILTER_DECLSPEC_ATTRIBUTES_1_END
#  define __DPL_FILTER_DECLSPEC_ATTRIBUTES_2_END

#  define __DPL_DECLSPEC(LIST)                         \
      __DPL_DECLSPEC_SCOPE(__DPL_BUILD_ATTRIBUTE_LIST( \
          __DPL_TRANSLATE_ATTRIBUTE(__DPL_FILTER_DECLSPEC_ATTRIBUTES(LIST))))
#else
#  define __DPL_DECLSPEC(LIST)
#endif

#if DPL_COMPILER_MSVC

#  define __DPL_TRANSLATE_MSVC_EXT_ATTRIBUTE(ARGS) \
      DPL_SWAP_CONCAT(_END, __DPL_TRANSLATE_MSVC_EXT_ATTRIBUTE_1 ARGS)
#  define __DPL_TRANSLATE_MSVC_EXT_ATTRIBUTE_0(NAME) DPL_CONCAT(__DPL_ATTRIBUTE_, NAME)
#  if DPL_MSVC_PREPROCESSOR
#    define __DPL_TRANSLATE_MSVC_EXT_ATTRIBUTE_1(NAME) \
        DPL_PASTE(__DPL_TRANSLATE_MSVC_EXT_ATTRIBUTE_0(NAME) __DPL_TRANSLATE_MSVC_EXT_ATTRIBUTE_2)
#    define __DPL_TRANSLATE_MSVC_EXT_ATTRIBUTE_2(NAME) \
        DPL_PASTE(__DPL_TRANSLATE_MSVC_EXT_ATTRIBUTE_0(NAME) __DPL_TRANSLATE_MSVC_EXT_ATTRIBUTE_1)
#  else
#    define __DPL_TRANSLATE_MSVC_EXT_ATTRIBUTE_1(NAME) \
        __DPL_TRANSLATE_MSVC_EXT_ATTRIBUTE_0(NAME) __DPL_TRANSLATE_MSVC_EXT_ATTRIBUTE_2
#    define __DPL_TRANSLATE_MSVC_EXT_ATTRIBUTE_2(NAME) \
        __DPL_TRANSLATE_MSVC_EXT_ATTRIBUTE_0(NAME) __DPL_TRANSLATE_MSVC_EXT_ATTRIBUTE_1
#  endif
#  define __DPL_TRANSLATE_MSVC_EXT_ATTRIBUTE_1_END
#  define __DPL_TRANSLATE_MSVC_EXT_ATTRIBUTE_2_END

#  define __DPL_FILTER_MSVC_EXT_ATTRIBUTES(ARGS) \
      DPL_SWAP_CONCAT(_END, __DPL_FILTER_MSVC_EXT_ATTRIBUTES_1 ARGS)
#  define __DPL_FILTER_MSVC_EXT_ATTRIBUTES_1(NAME)                                   \
      __DPL_ATTRIBUTE_FILTER(NAME, DPL_CONCAT(__DPL_ATTRIBUTE_TYPE_MSVC_EXT_, NAME)) \
      __DPL_FILTER_MSVC_EXT_ATTRIBUTES_2
#  define __DPL_FILTER_MSVC_EXT_ATTRIBUTES_2(NAME)                                   \
      __DPL_ATTRIBUTE_FILTER(NAME, DPL_CONCAT(__DPL_ATTRIBUTE_TYPE_MSVC_EXT_, NAME)) \
      __DPL_FILTER_MSVC_EXT_ATTRIBUTES_1
#  define __DPL_FILTER_MSVC_EXT_ATTRIBUTES_1_END
#  define __DPL_FILTER_MSVC_EXT_ATTRIBUTES_2_END
#  define __DPL_MSVC_EXT_ATTRIBUTES(LIST) \
      __DPL_TRANSLATE_MSVC_EXT_ATTRIBUTE(__DPL_FILTER_MSVC_EXT_ATTRIBUTES(LIST))
#else
#  define __DPL_MSVC_EXT_ATTRIBUTES(LIST)
#endif

#define __DPL_ATOMIZE_ATTRIBUTE_1(NAME) DPL_CONCAT(__DPL_ATTRIBUTE_, NAME)
#define __DPL_ATOMIZE_ATTRIBUTE_0(NAME) (NAME)
#define __DPL_ATOMIZE_ATTRIBUTE(NAME) \
    DPL_PASTE(DPL_APPEND_IS_EMPTY(    \
        __DPL_ATOMIZE_ATTRIBUTE_, DPL_CONCAT(__DPL_ATTRIBUTE_TYPE_AGGREGATE_, NAME))(NAME))

#define __DPL_ATTRIBUTE_ATOMIZATION(ARGS) DPL_SWAP_CONCAT(_END, __DPL_ATTRIBUTE_ATOMIZATION_1 ARGS)
#if DPL_MSVC_PREPROCESSOR
#  define __DPL_ATTRIBUTE_ATOMIZATION_1(NAME) \
      DPL_PASTE(__DPL_ATOMIZE_ATTRIBUTE(NAME) __DPL_ATTRIBUTE_ATOMIZATION_2)
#  define __DPL_ATTRIBUTE_ATOMIZATION_2(NAME) \
      DPL_PASTE(__DPL_ATOMIZE_ATTRIBUTE(NAME) __DPL_ATTRIBUTE_ATOMIZATION_1)
#else
#  define __DPL_ATTRIBUTE_ATOMIZATION_1(NAME) \
      __DPL_ATOMIZE_ATTRIBUTE(NAME) __DPL_ATTRIBUTE_ATOMIZATION_2
#  define __DPL_ATTRIBUTE_ATOMIZATION_2(NAME) \
      __DPL_ATOMIZE_ATTRIBUTE(NAME) __DPL_ATTRIBUTE_ATOMIZATION_1
#endif
#define __DPL_ATTRIBUTE_ATOMIZATION_1_END
#define __DPL_ATTRIBUTE_ATOMIZATION_2_END

#define __DPL_EXPAND_ATOMIC_ATTRIBUTES(LIST) \
    __DPL_CPP_ATTRIBUTES(LIST)               \
    __DPL_GNU_ATTRIBUTES(LIST) __DPL_DECLSPEC(LIST) __DPL_MSVC_EXT_ATTRIBUTES(LIST)

#define __DPL_ATTRIBUTES(LIST) __DPL_EXPAND_ATOMIC_ATTRIBUTES(__DPL_ATTRIBUTE_ATOMIZATION(LIST))

/**
 * Limit to 4 instead of using APPLY due to slow preprocessing
 */
#define __DPL_TO_ITERABLE_0(_0, _1, _2, _3, IMPL, ...) IMPL
#define __DPL_TO_ITERABLE(...)                                                 \
    __DPL_TO_ITERABLE_0(__VA_ARGS__, __DPL_TO_ITERABLE_4, __DPL_TO_ITERABLE_3, \
        __DPL_TO_ITERABLE_2, __DPL_TO_ITERABLE_1)                              \
    (__VA_ARGS__)
#define __DPL_TO_ITERABLE_4(_0, _1, _2, _3) (_0)(_1)(_2)(_3)
#define __DPL_TO_ITERABLE_3(_0, _1, _2) (_0)(_1)(_2)
#define __DPL_TO_ITERABLE_2(_0, _1) (_0)(_1)
#define __DPL_TO_ITERABLE_1(_0) (_0)

/**
 * Note: DPL_APPLY_MACRO slows down preprocessing by quite a bit
 * Compared with DPL_ATTRIBUTES disabled
 * preprocesses in ~3x without DPL_ATTRIBUTES when using __DPL_TO_ITERABLE
 * preprocesses in ~5x without DPL_ATTRIBUTES when using DPL_APPLY_MACRO
 */
#define DPL_ATTRIBUTES(...) __DPL_ATTRIBUTES(__DPL_TO_ITERABLE(__VA_ARGS__))
#define DPL_ATTRIBUTE(ATTR) __DPL_ATTRIBUTES((ATTR))

#define DPL_CPP_ATTRIBUTES(...) __DPL_CPP_ATTRIBUTES(__DPL_TO_ITERABLE(__VA_ARGS__))
#define DPL_CPP_ATTRIBUTE(ATTR) __DPL_CPP_ATTRIBUTES((ATTR))

#define DPL_GNU_ATTRIBUTES(...) __DPL_GNU_ATTRIBUTES(__DPL_TO_ITERABLE(__VA_ARGS__))
#define DPL_GNU_ATTRIBUTE(ATTR) __DPL_GNU_ATTRIBUTES((ATTR))

#define DPL_DECLSPEC_ATTRIBUTES(...) __DPL_DECLSPEC(__DPL_TO_ITERABLE(__VA_ARGS__))
#define DPL_DECLSPEC_ATTRIBUTE(ATTR) __DPL_DECLSPEC((ATTR))

#define __DPL_NONEMPTY_ATTRIBUTE(ARG) !DPL_IS_EMPTY(ARG)
#define __DPL_HAS_ATTRIBUTE(ARGS)                                           \
    __DPL_NONEMPTY_ATTRIBUTE(__DPL_FILTER_CPP_ATTRIBUTES(ARGS)) ||          \
        __DPL_NONEMPTY_ATTRIBUTE(__DPL_FILTER_GNU_ATTRIBUTES(ARGS)) ||      \
        __DPL_NONEMPTY_ATTRIBUTE(__DPL_FILTER_DECLSPEC_ATTRIBUTES(ARGS)) || \
        __DPL_NONEMPTY_ATTRIBUTE(__DPL_FILTER_MSVC_EXT_ATTRIBUTES(ARGS))

#define DPL_HAS_ATTRIBUTE(NAME) __DPL_HAS_ATTRIBUTE(__DPL_ATTRIBUTE_ATOMIZATION((NAME)))

#define DPL_HAS_AGGREGATE_ATTRIBUTE(NAME) \
    DPL_IS_EMPTY(DPL_CONCAT(__DPL_ATTRIBUTE_TYPE_AGGREGATE_, NAME))
